---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "opencost.fullname" . }}
  labels:
    {{- include "opencost.labels" . | nindent 4 }}
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "opencost.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "opencost.fullname" . }}
    namespace: {{ .Release.Namespace }}
