---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencost.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "opencost.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "opencost.selectorLabels" . | nindent 4 }}
  ports:
    - name: opencost
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 9003
  {{- if .Values.ui }}
    - name: opencost-ui
      protocol: TCP
      port: {{ .Values.ui.service.port }}
      targetPort: 9090
  {{- end }}
