---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opencost.fullname" . }}
  labels:
    {{- include "opencost.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
