# See: https://minikube.sigs.k8s.io/docs/tutorials/setup_minikube_in_github_actions
name: Helm

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Test Helm chart"
    steps:
    - uses: actions/checkout@v3
    - name: "Start minikube"
      id: minikube
      uses: medyagh/setup-minikube@latest
